import { describe, expect, it } from "bun:test";
import {
  LorcanaMultiplayerTestEngine,
  PLAYER_ONE,
  PLAYER_TWO,
  createMockCharacter,
} from "@tcg/lorcana-engine/testing";
import { theMobSong } from "@tcg/lorcana-cards/cards/004";

import { snapshotPendingPrompt } from "./prompt-snapshot.js";

// The Mob Song: "Deal 3 damage to up to 3 chosen characters and/or locations."
// Defined at lorcana-cards/src/cards/004/actions/198-the-mob-song.ts with
// `count: { upTo: 3 }`, `owner: "any"`, `zones: ["play"]`,
// `cardTypes: ["character", "location"]`.
//
// UI-level behaviour under test:
//  - `effectType === "deal-damage"` so the ResolutionTargetOverlay renders.
//  - `maxSelections === 3`, `minSelections === 0` (player may choose 0–3 targets).
//  - Three slots are generated by the prompt builder (one per maxSelections).
//  - Candidates include characters from BOTH players (owner: "any").
//  - Picking fewer than 3 targets is valid (no slot minimum).

const p1CharA = createMockCharacter({
  id: "mob-song-p1-a",
  name: "Villager One",
  cost: 2,
  strength: 2,
  willpower: 4,
  lore: 1,
});

const p1CharB = createMockCharacter({
  id: "mob-song-p1-b",
  name: "Villager Two",
  cost: 2,
  strength: 2,
  willpower: 4,
  lore: 1,
});

const p2CharA = createMockCharacter({
  id: "mob-song-p2-a",
  name: "Beast",
  cost: 5,
  strength: 5,
  willpower: 7,
  lore: 2,
});

const p2CharB = createMockCharacter({
  id: "mob-song-p2-b",
  name: "Beast's Servant",
  cost: 3,
  strength: 3,
  willpower: 5,
  lore: 1,
});

describe("The Mob Song | UI prompt", () => {
  it("opens a deal-damage prompt with 3 slots and minSelections 0", () => {
    const testEngine = LorcanaMultiplayerTestEngine.createWithFixture(
      {
        hand: [theMobSong],
        inkwell: theMobSong.cost,
        play: [
          { card: p1CharA, isDrying: false },
          { card: p1CharB, isDrying: false },
        ],
      },
      {
        play: [p2CharA, p2CharB],
      },
    );

    expect(testEngine.asPlayerOne().playCard(theMobSong)).toBeSuccessfulCommand();

    const snapshot = snapshotPendingPrompt(testEngine, { playerId: PLAYER_ONE });

    expect(snapshot).not.toBeNull();
    expect(snapshot?.kind).toBe("target-selection");
    expect(snapshot?.effectType).toBe("deal-damage");

    // upTo:3 means 0–3 selections are valid.
    expect(snapshot?.minSelections).toBe(0);
    expect(snapshot?.maxSelections).toBe(3);

    // The prompt builder generates one slot per maxSelections so the user can
    // fill them sequentially and stop early.
    expect(snapshot?.prompt?.slots).toHaveLength(3);
    expect(snapshot?.prompt?.slots.map((slot) => slot.label)).toEqual([
      "Deal damage to",
      "Deal damage to",
      "Deal damage to",
    ]);
  });

  it("includes characters from both players as candidates (owner: any)", () => {
    const testEngine = LorcanaMultiplayerTestEngine.createWithFixture(
      {
        hand: [theMobSong],
        inkwell: theMobSong.cost,
        play: [
          { card: p1CharA, isDrying: false },
          { card: p1CharB, isDrying: false },
        ],
      },
      {
        play: [p2CharA, p2CharB],
      },
    );

    expect(testEngine.asPlayerOne().playCard(theMobSong)).toBeSuccessfulCommand();

    const snapshot = snapshotPendingPrompt(testEngine, { playerId: PLAYER_ONE });

    const p1aId = testEngine.asPlayerOne().getCard(p1CharA).id;
    const p1bId = testEngine.asPlayerOne().getCard(p1CharB).id;
    const p2aId = testEngine.asPlayerTwo().getCard(p2CharA).id;
    const p2bId = testEngine.asPlayerTwo().getCard(p2CharB).id;

    // All four characters (from both sides) must be in the engine's candidate list.
    expect(snapshot?.cardCandidateIds).toContain(p1aId);
    expect(snapshot?.cardCandidateIds).toContain(p1bId);
    expect(snapshot?.cardCandidateIds).toContain(p2aId);
    expect(snapshot?.cardCandidateIds).toContain(p2bId);

    // The first slot's candidateEntries must include characters from both sides.
    const candidateIds = snapshot?.prompt?.candidateEntries.map((e) => e.cardId) ?? [];
    expect(candidateIds).toContain(p1aId);
    expect(candidateIds).toContain(p1bId);
    expect(candidateIds).toContain(p2aId);
    expect(candidateIds).toContain(p2bId);
  });

  it("excludes already-selected cards from subsequent slot candidates", () => {
    const testEngine = LorcanaMultiplayerTestEngine.createWithFixture(
      {
        hand: [theMobSong],
        inkwell: theMobSong.cost,
        play: [
          { card: p1CharA, isDrying: false },
          { card: p1CharB, isDrying: false },
        ],
      },
      {
        play: [p2CharA, p2CharB],
      },
    );

    expect(testEngine.asPlayerOne().playCard(theMobSong)).toBeSuccessfulCommand();

    const p1aId = testEngine.asPlayerOne().getCard(p1CharA).id;
    const p2aId = testEngine.asPlayerTwo().getCard(p2CharA).id;

    // Simulate: user has selected p1CharA in slot 0, now viewing slot 1.
    const snapshot = snapshotPendingPrompt(testEngine, {
      playerId: PLAYER_ONE,
      selectedTargets: [p1aId],
    });

    // Slot 0 is filled; slot 1 is now active.
    expect(snapshot?.prompt?.activeSlotIndex).toBe(1);

    // p1CharA (already in slot 0) must not appear in slot 1's candidates.
    const slot1Candidates = snapshot?.prompt?.candidateEntries.map((e) => e.cardId) ?? [];
    expect(slot1Candidates).not.toContain(p1aId);
    expect(slot1Candidates).toContain(p2aId);
  });

  it("does not open any prompt when there are no valid targets", () => {
    const testEngine = LorcanaMultiplayerTestEngine.createWithFixture(
      {
        hand: [theMobSong],
        inkwell: theMobSong.cost,
      },
      {},
    );

    expect(testEngine.asPlayerOne().playCard(theMobSong)).toBeSuccessfulCommand();

    expect(snapshotPendingPrompt(testEngine, { playerId: PLAYER_ONE })).toBeNull();
    expect(snapshotPendingPrompt(testEngine, { playerId: PLAYER_TWO })).toBeNull();
  });

  it("prompt is visible from player two's view with the same candidates", () => {
    const testEngine = LorcanaMultiplayerTestEngine.createWithFixture(
      {
        hand: [theMobSong],
        inkwell: theMobSong.cost,
        play: [{ card: p1CharA, isDrying: false }],
      },
      {
        play: [p2CharA],
      },
    );

    expect(testEngine.asPlayerOne().playCard(theMobSong)).toBeSuccessfulCommand();

    const p1aId = testEngine.asPlayerOne().getCard(p1CharA).id;
    const p2aId = testEngine.asPlayerTwo().getCard(p2CharA).id;

    const fromP1 = snapshotPendingPrompt(testEngine, { playerId: PLAYER_ONE });
    const fromP2 = snapshotPendingPrompt(testEngine, { playerId: PLAYER_TWO });

    for (const snapshot of [fromP1, fromP2]) {
      expect(snapshot?.effectType).toBe("deal-damage");
      expect(snapshot?.cardCandidateIds).toContain(p1aId);
      expect(snapshot?.cardCandidateIds).toContain(p2aId);
    }
  });
});
