import type { PlayerTargetDSL } from "./target-dsl";
import type {
  CharacterTargetEnum,
  ItemTargetEnum,
  LocationTargetEnum,
} from "../abilities/target-types";
import type { LorcanaCardTarget } from "./lorcana-target-dsl";

export const CHARACTER_ENUM_EXPANSIONS: Record<CharacterTargetEnum, LorcanaCardTarget> = {
  SELF: { selector: "self", context: { self: true }, cardTypes: ["character"] },
  THIS_CHARACTER: { selector: "self", context: { self: true }, cardTypes: ["character"] },
  CHOSEN_CHARACTER: {
    selector: "chosen",
    count: 1,
    owner: "any",
    zones: ["play"],
    cardTypes: ["character"],
  },
  CHOSEN_OPPOSING_CHARACTER: {
    selector: "chosen",
    count: 1,
    owner: "opponent",
    zones: ["play"],
    cardTypes: ["character"],
  },
  CHOSEN_CHARACTER_OF_YOURS: {
    selector: "chosen",
    count: 1,
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
  },
  ANOTHER_CHOSEN_CHARACTER: {
    selector: "chosen",
    count: 1,
    owner: "any",
    zones: ["play"],
    cardTypes: ["character"],
    excludeSelf: true,
  },
  ANOTHER_CHOSEN_CHARACTER_OF_YOURS: {
    selector: "chosen",
    count: 1,
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    excludeSelf: true,
  },
  ALL_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "any",
    zones: ["play"],
    cardTypes: ["character"],
  },
  ALL_OPPOSING_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "opponent",
    zones: ["play"],
    cardTypes: ["character"],
  },
  YOUR_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
  },
  YOUR_OTHER_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    excludeSelf: true,
  },
  YOUR_EXERTED_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "exerted" }],
  },
  YOUR_EVASIVE_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "has-keyword", keyword: "Evasive" }],
  },
  YOUR_OTHER_EVASIVE_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    excludeSelf: true,
    filters: [{ type: "has-keyword", keyword: "Evasive" }],
  },
  OPPOSING_EVASIVE_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "opponent",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "has-keyword", keyword: "Evasive" }],
  },
  SEVEN_DWARFS_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "has-classification", classification: "Seven Dwarfs" }],
  },
  YOUR_OTHER_SEVEN_DWARFS_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "has-classification", classification: "Seven Dwarfs" }],
    excludeSelf: true,
  },
  YOUR_HERO_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "has-classification", classification: "Hero" }],
  },
  YOUR_QUEEN_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "has-classification", classification: "Queen" }],
  },
  YOUR_OTHER_HERO_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "has-classification", classification: "Hero" }],
    excludeSelf: true,
  },
  YOUR_BODYGUARD_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "has-keyword", keyword: "Bodyguard" }],
  },
  YOUR_PIRATE_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "has-classification", classification: "Pirate" }],
  },
  YOUR_PUPPY_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "has-classification", classification: "Puppy" }],
  },
  EACH_CHARACTER: {
    selector: "each",
    count: "all",
    owner: "any",
    zones: ["play"],
    cardTypes: ["character"],
  },
  EACH_OPPOSING_CHARACTER: {
    selector: "each",
    count: "all",
    owner: "opponent",
    zones: ["play"],
    cardTypes: ["character"],
  },
  CHOSEN_DAMAGED_CHARACTER: {
    selector: "chosen",
    count: 1,
    owner: "any",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "status", status: "damaged" }],
  },
  CHOSEN_DAMAGED_OPPOSING_CHARACTER: {
    selector: "chosen",
    count: 1,
    owner: "opponent",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "status", status: "damaged" }],
  },
  CHOSEN_EXERTED_CHARACTER: {
    selector: "chosen",
    count: 1,
    owner: "any",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "exerted" }],
  },
  CHOSEN_OTHER_CHARACTER: {
    selector: "chosen",
    count: 1,
    owner: "any",
    zones: ["play"],
    cardTypes: ["character"],
    excludeSelf: true,
  },
  CHOSEN_CHALLENGED_CHARACTER: {
    selector: "chosen",
    count: 1,
    owner: "opponent",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "challenge-role", role: "defender" }],
  },
  YOUR_CHOSEN_CHARACTER: {
    selector: "chosen",
    count: 1,
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
  },
  YOUR_CHOSEN_DAMAGED_CHARACTER: {
    selector: "chosen",
    count: 1,
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "status", status: "damaged" }],
  },
  YOUR_CHOSEN_VILLAIN: {
    selector: "chosen",
    count: 1,
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "has-classification", classification: "Villain" }],
  },
  YOUR_CHOSEN_ITEM: {
    selector: "chosen",
    count: 1,
    owner: "you",
    zones: ["play"],
    cardTypes: ["item"],
  },
  YOUR_OTHER_CHARACTER: {
    selector: "chosen",
    count: 1,
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    excludeSelf: true,
  },
  YOUR_OTHER_2_CHARACTERS: {
    selector: "chosen",
    count: { exactly: 2 },
    owner: "you",
    zones: ["play"],
    cardTypes: ["character"],
    excludeSelf: true,
  },
  UP_TO_2_CHOSEN_CHARACTERS: {
    selector: "chosen",
    count: { upTo: 2 },
    owner: "any",
    zones: ["play"],
    cardTypes: ["character"],
  },
  CHOSEN_OPPOSING_CHARACTER_3_STRENGTH_OR_LESS: {
    selector: "chosen",
    count: 1,
    owner: "opponent",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "strength-comparison", comparison: "less-or-equal", value: 3 }],
  },
  "challenging-character": {
    selector: "self",
    context: { attacker: true },
    cardTypes: ["character"],
  },
  "challenged-character": {
    selector: "self",
    context: { defender: true },
    cardTypes: ["character"],
  },
  OPPOSING_CHARACTERS: {
    selector: "all",
    count: "all",
    owner: "opponent",
    zones: ["play"],
    cardTypes: ["character"],
  },
  CHOSEN_OPPOSING_DAMAGED_CHARACTER: {
    selector: "chosen",
    count: 1,
    owner: "opponent",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "status", status: "damaged" }],
  },
  CHOSEN_CHARACTER_IN_DISCARD: {
    selector: "chosen",
    count: 1,
    owner: "any",
    zones: ["discard"],
    cardTypes: ["character"],
  },
  CHOSEN_CARD_IN_DISCARD: {
    selector: "chosen",
    count: 1,
    owner: "any",
    zones: ["discard"],
  },
  CHOSEN_CARD_FROM_DISCARD: {
    selector: "chosen",
    count: 1,
    owner: "any",
    zones: ["discard"],
  },
  CHOSEN_CARD_FROM_HAND: {
    selector: "chosen",
    count: 1,
    owner: "any",
    zones: ["hand"],
  },
  CHOSEN_CHARACTER_OR_LOCATION: {
    selector: "chosen",
    count: 1,
    owner: "any",
    zones: ["play"],
    cardTypes: ["character", "location"],
  },
  CHOSEN_ITEM_OR_LOCATION: {
    selector: "chosen",
    count: 1,
    owner: "any",
    zones: ["play"],
    cardTypes: ["item", "location"],
  },
  CHOSEN_CHARACTER_ITEM_OR_LOCATION: {
    selector: "chosen",
    count: 1,
    owner: "any",
    zones: ["play"],
    cardTypes: ["character", "item", "location"],
  },
  CHOSEN_CHARACTERS: {
    selector: "chosen",
    count: { upTo: 2 },
    owner: "any",
    zones: ["play"],
    cardTypes: ["character"],
  },
  CHOSEN_OPPONENT: {
    selector: "chosen",
    count: 1,
    owner: "any",
  },
  REVEALED_CARD: {
    selector: "chosen",
    count: 1,
    owner: "any",
  },
  TOP_OF_DECK: {
    selector: "any",
    count: 1,
    owner: "you",
    zones: ["deck"],
  },
  TRIGGERING_CHARACTER: {
    reference: "trigger-source",
    cardTypes: ["character"],
  },
  TRIGGERING_CARD: {
    reference: "trigger-source",
  },
} as unknown as Record<CharacterTargetEnum, LorcanaCardTarget>;

export const ITEM_ENUM_EXPANSIONS: Record<ItemTargetEnum, LorcanaCardTarget> = {
  CHOSEN_ITEM: { selector: "chosen", count: 1, owner: "any", zones: ["play"], cardTypes: ["item"] },
  CHOSEN_OPPOSING_ITEM: {
    selector: "chosen",
    count: 1,
    owner: "opponent",
    zones: ["play"],
    cardTypes: ["item"],
  },
  YOUR_ITEMS: { selector: "all", count: "all", owner: "you", zones: ["play"], cardTypes: ["item"] },
  YOUR_ITEM: { selector: "chosen", count: 1, owner: "you", zones: ["play"], cardTypes: ["item"] },
  ALL_ITEMS: { selector: "all", count: "all", owner: "any", zones: ["play"], cardTypes: ["item"] },
  ALL_OPPOSING_ITEMS: {
    selector: "all",
    count: "all",
    owner: "opponent",
    zones: ["play"],
    cardTypes: ["item"],
  },
  THIS_ITEM: { selector: "self", context: { self: true }, cardTypes: ["item"] },
} as const;

export const LOCATION_ENUM_EXPANSIONS: Record<LocationTargetEnum, LorcanaCardTarget> = {
  CHOSEN_LOCATION: {
    selector: "chosen",
    count: 1,
    owner: "any",
    zones: ["play"],
    cardTypes: ["location"],
  },
  CHOSEN_OPPOSING_LOCATION: {
    selector: "chosen",
    count: 1,
    owner: "opponent",
    zones: ["play"],
    cardTypes: ["location"],
  },
  YOUR_LOCATIONS: {
    selector: "all",
    count: "all",
    owner: "you",
    zones: ["play"],
    cardTypes: ["location"],
  },
  ALL_OPPOSING_LOCATIONS: {
    selector: "all",
    count: "all",
    owner: "opponent",
    zones: ["play"],
    cardTypes: ["location"],
  },
  THIS_LOCATION: { selector: "self", context: { self: true }, cardTypes: ["location"] },
  CHARACTERS_HERE: {
    selector: "all",
    count: "all",
    owner: "any",
    zones: ["play"],
    cardTypes: ["character"],
    filters: [{ type: "same-location-as-source" }],
  },
} as const;

export const PLAYER_TARGET_EXPANSIONS: Record<string, PlayerTargetDSL> = {
  CONTROLLER: { selector: "you" },
  SELF: { selector: "you" },
  OPPONENT: { selector: "opponent" },
  OPPONENTS: { selector: "opponent" }, // Alias for OPPONENT — engine is 1v1 only
  EACH_OPPONENT: { selector: "opponent" }, // Alias for OPPONENT — engine is 1v1 only
  EACH_PLAYER: { selector: "each-player" },
  ALL_PLAYERS: { selector: "each-player" },
  CHOSEN_PLAYER: { selector: "chosen" },
  CHALLENGING_PLAYER: { selector: "challenging-player" },
};

export const CHARACTER_TARGET_ENUMS = new Set<string>(Object.keys(CHARACTER_ENUM_EXPANSIONS));
export const ITEM_TARGET_ENUMS = new Set<string>(Object.keys(ITEM_ENUM_EXPANSIONS));
export const LOCATION_TARGET_ENUMS = new Set<string>(Object.keys(LOCATION_ENUM_EXPANSIONS));
export const ALL_TARGET_ENUMS = new Set<string>([
  ...CHARACTER_TARGET_ENUMS,
  ...ITEM_TARGET_ENUMS,
  ...LOCATION_TARGET_ENUMS,
]);
