#!/usr/bin/env bun
/**
 * Card Generation Script
 *
 * Generates card data from ravensburger-input.json and lorcast-input.json
 * into the src/cards directory (individual TypeScript files) and
 * src/data directory (JSON reference files).
 *
 * Data source strategy:
 *   - Card text: Lorcast (has symbols like {S}, {I}, {D})
 *   - All other data: Ravensburger (stats, images, set info)
 *
 * Card identity and canonicalId:
 *   - One CardDefinition per printing (each set × card number × variant).
 *   - Card id MUST be a 3-character short id (e.g. "wrC"). Do NOT use printing-id format (e.g. set1-098).
 *   - Identity = full name (name + " - " + subtitle). Same full name ⇒ same canonicalId. Each printing gets a unique 3-char id.
 *   - canonicalId: must begin with "ci_" (e.g. ci_xxx).
 *   - Short IDs are 3 chars (0-9, a-z, A-Z); IDs live only on cards; lookups derived from canonical-cards in code.
 *
 * Scope: only EXPANSION sets are included (QUEST and gateway sets are excluded). All rarities within
 * expansion sets are included (common, uncommon, rare, super rare, legendary, plus specialRarity: enchanted, epic, iconic, promo, challenge).
 *
 * Usage:
 *   bun packages/lorcana-cards/scripts/generate-cards.ts
 *
 * Output files:
 *   - src/cards/{set}/{type}/{card}.ts (individual card files)
 *   - src/cards/catalog-data.ts (main aggregator)
 *   - src/cards/index.ts (entry point)
 *   - src/cards/types.ts (type definitions)
 *   - src/data/sets.json
 *   - src/data/canonical-cards.json
 *   - src/data/cards.aux.printing-metadata.json (minimal runtime metadata, replaces printings.json)
 *   - src/data/cards.aux.kv.json (generated by generate-card-aux.ts)
 *   - src/data/cards.aux.validation-report.json (generated by generate-card-aux.ts)
 *
 * Note: printings.json is no longer generated. Use cards.aux.printing-metadata.json + cards.aux.kv.json instead.
 */

import fs from "node:fs";
import path from "node:path";
import { generateCanonicalCardsFromPrintings } from "./generators/canonical-generator";
import {
  generateCardFiles,
  getOverwrittenFiles,
  resetOverwrittenFiles,
} from "./generators/file-generator";
import { assignPrintingIds } from "./generators/id-generator";
import {
  computePrintingIdsInOrder,
  calculateSetTotals,
  generatePrintingsFromItems,
} from "./generators/printings-generator";
import { generateSets, updateSetTotalCards } from "./generators/sets-generator";
import {
  expandToPrintingItems,
  getAllCards,
  getCardSets,
  getFullNameFromCard,
  loadRavensburgerJson,
} from "./parsers/input-parser";
import type { PrintingItem } from "./parsers/input-parser";
import {
  loadLorcastAndBuildIndexes,
  type LorcastFullIndex,
  type LorcastTextIndex,
} from "./parsers/lorcast-parser";
import { loadGalleryJson, mergeGalleryFallback } from "./parsers/gallery-parser";
import type {
  CanonicalCard,
  CardPrinting,
  CardPrintingMetadata,
  InputCard,
  PipelineIdMapping,
  SetDefinition,
} from "./types";
import {
  validateCanonicalIdNames,
  validateFullNameCanonicalId,
  validatePipelineIdMapping,
  validateSourceIdsMatchCanonical,
  validateUniqueCardIds,
} from "./validators/card-validation";

const DATA_OUTPUT_DIR = path.resolve(__dirname, "../src/data");
const CARDS_OUTPUT_DIR = path.resolve(__dirname, "../src/cards");
const CANONICAL_CARDS_PATH = path.resolve(DATA_OUTPUT_DIR, "canonical-cards.json");

interface LoadDataResult {
  input: ReturnType<typeof loadRavensburgerJson>;
  lorcastIndex: LorcastTextIndex;
  lorcastFullIndex: LorcastFullIndex;
}

interface SetsPhaseResult {
  sets: Record<string, SetDefinition>;
  expansionSetIds: Set<string>;
  allCards: ReturnType<typeof getAllCards>;
}

interface PrintingsPhaseResult {
  pipelineIdMapping: PipelineIdMapping;
  printings: Record<string, CardPrinting>;
  printingItems: PrintingItem[];
  printingIdsInOrder: string[];
}

/** Match the top-level `id: "..."` line in a card TypeScript file. */
const CARD_ID_RE = /^\s{0,4}id:\s*"([^"]+)"/m;

/**
 * Scan existing TypeScript card source files and extract their `id` values,
 * keyed by printingId (derived from `reprints[0]` or from the file path).
 * Used to cross-check against the newly-generated canonical-cards.json.
 */
function readSourceCardIds(cardsDir: string): Record<string, string> {
  const result: Record<string, string> = {};

  function walk(dir: string): void {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
        continue;
      }
      if (
        !entry.isFile() ||
        !entry.name.endsWith(".ts") ||
        entry.name.endsWith(".test.ts") ||
        entry.name.endsWith(".i18n.ts") ||
        entry.name === "index.ts" ||
        entry.name === "types.ts" ||
        entry.name === "catalog-data.ts" ||
        entry.name === "catalog-integrity.test.ts"
      ) {
        continue;
      }

      const content = fs.readFileSync(full, "utf-8");

      const idMatch = content.match(CARD_ID_RE);
      if (!idMatch?.[1]) continue;
      const sourceId = idMatch[1];

      // Extract reprints field to find the printingId
      const reprintsMatch = content.match(/reprints:\s*\[([^\]]+)\]/);
      if (!reprintsMatch?.[1]) continue;
      const firstReprint = reprintsMatch[1].match(/"([^"]+)"/)?.[1];
      if (!firstReprint) continue;

      result[firstReprint] = sourceId;
    }
  }

  walk(cardsDir);
  return result;
}

/**
 * Load existing canonical cards if available (for stable IDs; ids live only on cards).
 */
function loadExistingCanonicalCards(): Record<string, CanonicalCard> | undefined {
  try {
    if (fs.existsSync(CANONICAL_CARDS_PATH)) {
      const content = fs.readFileSync(CANONICAL_CARDS_PATH, "utf-8");
      return JSON.parse(content) as Record<string, CanonicalCard>;
    }
  } catch {
    // No existing canonical cards; will generate fresh canonicalIds
  }
  return undefined;
}

/**
 * Write JSON file with pretty formatting
 */
function writeJson(filePath: string, data: unknown): void {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), "utf-8");
}

function loadData(): LoadDataResult {
  console.log("🔍 Loading card data from dual sources...");
  console.log("   - Ravensburger: stats, images, set info");
  console.log("   - Lorcast: card text with symbols ({S}, {I}, {D})");

  console.log("\n📖 Loading Lorcast data...");
  const { textIndex: lorcastIndex, fullIndex: lorcastFullIndex } = loadLorcastAndBuildIndexes();

  console.log("\n📚 Loading Ravensburger data...");
  const rawInput = loadRavensburgerJson();

  console.log("\n🖼️  Loading gallery fallback...");
  const gallery = loadGalleryJson();
  const { input, stats: galleryStats } = mergeGalleryFallback(rawInput, gallery);
  console.log(
    `  Gallery: ${galleryStats.total} entries (${galleryStats.alreadyInRavensburger} already in Ravensburger, ${galleryStats.seeded} seeded as fallback, ${galleryStats.skippedUnknownSet} skipped due to unknown set)`,
  );

  return { input, lorcastIndex, lorcastFullIndex };
}

function buildSetsAndFilterExpansion(input: LoadDataResult["input"]): SetsPhaseResult {
  console.log("📚 Generating sets...");
  const cardSets = getCardSets(input);
  const expansionSets = cardSets.filter((set) => set.type === "EXPANSION");
  const sets = generateSets(expansionSets);
  const expansionSetIds = new Set(Object.keys(sets));
  console.log(
    `  Found ${Object.keys(sets).length} expansion sets (filtered ${cardSets.length - expansionSets.length} non-expansion sets)`,
  );

  console.log("📦 Processing cards...");
  const allCardsRaw = getAllCards(input);
  const allCards = allCardsRaw.filter((card) =>
    card.card_sets.some((setId) => expansionSetIds.has(setId)),
  );
  console.log(
    `  Found ${allCards.length} expansion card entries (filtered ${allCardsRaw.length - allCards.length} non-expansion cards)`,
  );

  return { sets, expansionSetIds, allCards };
}

function buildIdMappingAndPrintings(
  sets: Record<string, SetDefinition>,
  expansionSetIds: Set<string>,
  allCards: SetsPhaseResult["allCards"],
): PrintingsPhaseResult {
  console.log("📤 Expanding to printing items...");
  const printingItems = expandToPrintingItems(allCards, expansionSetIds);
  console.log(`  ${printingItems.length} printing items`);

  console.log("🔑 Assigning unique 3-char id per printing (from existing cards when valid)...");
  const printingIdsInOrder = computePrintingIdsInOrder(printingItems);
  const existingCanonicalCards = loadExistingCanonicalCards();
  const pipelineIdMapping = assignPrintingIds(
    printingItems,
    printingIdsInOrder,
    (card) => getFullNameFromCard(card as InputCard),
    existingCanonicalCards,
  );
  console.log(`  ${Object.keys(pipelineIdMapping.byPrintingId).length} printing ids (3-char)`);

  console.log("🖨️ Generating printings...");
  const { printings, printingIdsInOrder: order } = generatePrintingsFromItems(
    printingItems,
    pipelineIdMapping,
    printingIdsInOrder,
  );
  const printingIdsInOrderResult = order;
  const printingList = Object.values(printings);
  const specialRarityCount = printingList.filter((p) => p.specialRarity).length;
  const bySpecialRarity: Record<string, number> = {};
  for (const p of printingList) {
    if (p.specialRarity) {
      bySpecialRarity[p.specialRarity] = (bySpecialRarity[p.specialRarity] ?? 0) + 1;
    }
  }
  console.log(
    `  Generated ${printingList.length} printings (incl. ${specialRarityCount} Enchanted/Epic/Iconic/Promo variants)`,
  );
  if (specialRarityCount > 0) {
    const parts = Object.entries(bySpecialRarity)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([k, n]) => `${k}: ${n}`);
    console.log(`  Special rarities: ${parts.join(", ")}`);
  }
  console.log(
    "  (Only expansion-set cards are included; promo-only cards outside expansions are not in this pipeline.)",
  );

  const setTotals = calculateSetTotals(printings);
  for (const [setId, total] of setTotals.entries()) {
    updateSetTotalCards(sets, setId, total);
  }

  return {
    pipelineIdMapping,
    printings,
    printingItems,
    printingIdsInOrder: printingIdsInOrderResult,
  };
}

function buildCanonicalAndValidate(
  printingItems: PrintingItem[],
  printingIdsInOrder: string[],
  pipelineIdMapping: PipelineIdMapping,
  lorcastIndex: LorcastTextIndex,
  lorcastFullIndex: LorcastFullIndex,
): Record<string, CanonicalCard> {
  console.log("🃏 Generating canonical cards (one per printing)...");
  const existingCanonicalCards = loadExistingCanonicalCards();
  const canonicalCards = generateCanonicalCardsFromPrintings(
    printingItems,
    printingIdsInOrder,
    pipelineIdMapping,
    lorcastIndex,
    lorcastFullIndex,
    existingCanonicalCards,
  );
  console.log(`  Generated ${Object.keys(canonicalCards).length} canonical cards`);

  console.log(
    "✔ Validating IDs and canonicalId/name (all cards checked before reporting errors)...",
  );
  const validationErrors: string[] = [];
  validationErrors.push(...validatePipelineIdMapping(pipelineIdMapping));
  validationErrors.push(...validateUniqueCardIds(canonicalCards));
  validationErrors.push(...validateCanonicalIdNames(canonicalCards));
  validationErrors.push(...validateFullNameCanonicalId(canonicalCards));

  // Cross-check existing TypeScript source files against the newly-generated
  // canonical data. Catches stale IDs when canonical-cards.json was updated
  // without regenerating the TypeScript files.
  const sourceIds = readSourceCardIds(CARDS_OUTPUT_DIR);
  const sourceErrors = validateSourceIdsMatchCanonical(sourceIds, canonicalCards);
  if (sourceErrors.length > 0) {
    console.warn(
      `  ⚠️  ${sourceErrors.length} TypeScript source file(s) have IDs that differ from canonical-cards.json (will be fixed by file generation):\n` +
        sourceErrors.map((e) => `    ${e}`).join("\n"),
    );
  }

  if (validationErrors.length > 0) {
    throw new Error(`Card validation failed:\n${validationErrors.join("\n")}`);
  }
  console.log("  ✅ Validation passed (no duplicate IDs; canonicalId/name consistent).");

  return canonicalCards;
}

/**
 * Transform full CardPrinting to minimal CardPrintingMetadata
 * Omits variants (image data) to reduce file size
 */
function toPrintingMetadata(printing: CardPrinting): CardPrintingMetadata {
  const meta: CardPrintingMetadata = {
    id: printing.id,
    gameCardId: printing.gameCardId,
    set: printing.set,
    cardNumber: printing.cardNumber,
    rarity: printing.rarity,
  };

  if (printing.specialRarity) {
    meta.specialRarity = printing.specialRarity;
  }
  if (printing.promoSheetCode) {
    meta.promoSheetCode = printing.promoSheetCode;
  }
  if (printing.author) {
    meta.author = printing.author;
  }
  if (printing.flavorText) {
    meta.flavorText = printing.flavorText;
  }
  if (printing.setRotationState) {
    meta.setRotationState = printing.setRotationState;
  }
  if (printing.sortNumber !== undefined) {
    meta.sortNumber = printing.sortNumber;
  }

  return meta;
}

function writeOutput(
  sets: Record<string, SetDefinition>,
  printings: Record<string, CardPrinting>,
  canonicalCards: Record<string, CanonicalCard>,
): void {
  console.log("📝 Writing JSON reference files...");
  writeJson(path.join(DATA_OUTPUT_DIR, "sets.json"), sets);
  console.log("  ✅ sets.json");

  // Generate minimal printing metadata (replaces full printings.json)
  const printingMetadata: Record<string, CardPrintingMetadata> = {};
  for (const [id, printing] of Object.entries(printings)) {
    printingMetadata[id] = toPrintingMetadata(printing);
  }
  writeJson(path.join(DATA_OUTPUT_DIR, "cards.aux.printing-metadata.json"), printingMetadata);
  console.log("  ✅ cards.aux.printing-metadata.json");

  // Note: printings.json is no longer generated - use cards.aux.printing-metadata.json
  writeJson(path.join(DATA_OUTPUT_DIR, "canonical-cards.json"), canonicalCards);
  console.log("  ✅ canonical-cards.json");
}

function generateCardFilesPhase(
  canonicalCards: Record<string, CanonicalCard>,
  sets: Record<string, SetDefinition>,
  printings: Record<string, CardPrinting>,
): void {
  console.log("\n📂 Generating card TypeScript files...");

  const generatableCards: Record<string, CanonicalCard> = {};
  let vanillaCount = 0;
  let stubbedCount = 0;
  const cardCategories: { vanilla: string[]; stubbed: string[] } = {
    vanilla: [],
    stubbed: [],
  };
  const displayName = (c: CanonicalCard) => (c.version ? `${c.name} - ${c.version}` : c.name);

  for (const [id, card] of Object.entries(canonicalCards)) {
    if (card.vanilla) {
      generatableCards[id] = card;
      vanillaCount++;
      cardCategories.vanilla.push(displayName(card));
    } else {
      generatableCards[id] = {
        ...card,
        missingImplementation: true,
        missingTests: true,
      };
      stubbedCount++;
      cardCategories.stubbed.push(displayName(card));
    }
  }

  console.log(`  Filtering to ${Object.keys(generatableCards).length} generatable cards:`);
  console.log(`    - Vanilla: ${vanillaCount}`);
  console.log(`    - Stubbed (ability parsing disabled): ${stubbedCount}`);

  const verboseLogPath = path.join(DATA_OUTPUT_DIR, "generation-verbose.log");
  const verboseLog: string[] = [
    "=".repeat(80),
    "CARD GENERATION VERBOSE LOG",
    "=".repeat(80),
    "",
    `Total generatable cards: ${Object.keys(generatableCards).length}`,
    "",
  ];
  if (cardCategories.vanilla.length > 0) {
    verboseLog.push(`VANILLA CARDS (${cardCategories.vanilla.length}):`);
    cardCategories.vanilla.forEach((name) => verboseLog.push(`  - ${name}`));
    verboseLog.push("");
  }
  if (cardCategories.stubbed.length > 0) {
    verboseLog.push(`STUBBED CARDS - ability parsing disabled (${cardCategories.stubbed.length}):`);
    cardCategories.stubbed.forEach((name) => verboseLog.push(`  - ${name}`));
    verboseLog.push("");
  }
  resetOverwrittenFiles();
  try {
    generateCardFiles(CARDS_OUTPUT_DIR, generatableCards, sets, printings);
  } finally {
    const overwritten = getOverwrittenFiles();
    if (overwritten.length > 0) {
      console.log(
        `  ⚠️  Overwrote ${overwritten.length} existing file(s) with different content (see verbose log)`,
      );
      verboseLog.push(`OVERWRITTEN FILES (${overwritten.length}):`);
      for (const filePath of overwritten) {
        verboseLog.push(`  - ${path.relative(process.cwd(), filePath)}`);
      }
      verboseLog.push("");
    }
    fs.writeFileSync(verboseLogPath, verboseLog.join("\n"), "utf-8");
    console.log(`  ✅ Verbose log: ${path.relative(process.cwd(), verboseLogPath)}`);
  }
}

/**
 * Main generation function – phased pipeline
 */
async function main() {
  const { input, lorcastIndex, lorcastFullIndex } = loadData();

  const { sets, expansionSetIds, allCards } = buildSetsAndFilterExpansion(input);

  const { pipelineIdMapping, printings, printingItems, printingIdsInOrder } =
    buildIdMappingAndPrintings(sets, expansionSetIds, allCards);

  const canonicalCards = buildCanonicalAndValidate(
    printingItems,
    printingIdsInOrder,
    pipelineIdMapping,
    lorcastIndex,
    lorcastFullIndex,
  );

  writeOutput(sets, printings, canonicalCards);

  generateCardFilesPhase(canonicalCards, sets, printings);

  console.log("\n📊 Summary:");
  console.log(`  Sets: ${Object.keys(sets).length}`);
  console.log(`  Canonical Cards: ${Object.keys(canonicalCards).length}`);
  console.log(`  Printings: ${Object.keys(printings).length}`);
  console.log(`  ID Mappings: ${Object.keys(pipelineIdMapping.byShortId).length}`);

  const cardsByType = new Map<string, number>();
  for (const card of Object.values(canonicalCards)) {
    const count = cardsByType.get(card.cardType) || 0;
    cardsByType.set(card.cardType, count + 1);
  }
  console.log("\n  Cards by type:");
  for (const [type, count] of cardsByType.entries()) {
    console.log(`    ${type}: ${count}`);
  }

  console.log("\n🎉 Done!");
}

// Run the script
main().catch((err) => {
  console.error("❌ Error generating cards:", err);
  process.exit(1);
});
