// .agents/skills/lorcana-rules/SKILL.md
// .agents/skills/lorcana-rules/indexes/by-section/06-abilities-effects-and-resolving.md

import { describe, expect, it } from "bun:test";
import type { ZoneId } from "@tcg/lorcana-types";
import { LorcanaMultiplayerTestEngine, PLAYER_ONE, PLAYER_TWO } from "@tcg/lorcana-engine/testing";
import {
  controlYourTemper,
  lefouBumbler,
  mickeyMouseTrueFriend,
  minnieMouseBelovedPrincess,
  simbaProtectiveCub,
} from "@tcg/lorcana-cards/cards/001";
import {
  flynnRiderHisOwnBiggestFan,
  grandDukeAdvisorToTheKing,
  improvise,
  thePrinceNeverGivesUp,
  tianaTruePrincess,
} from "@tcg/lorcana-cards/cards/002";
import { microbots, yokaiScientificSupervillain } from "@tcg/lorcana-cards/cards/006";
import { standOut } from "@tcg/lorcana-cards/cards/009";
import { elisaMazaTransformedGargoyle } from "@tcg/lorcana-cards/cards/011";

describe("# 6. ABILITIES, EFFECTS, AND RESOLVING", () => {
  describe("# 6.6. Ability Modifiers", () => {
    it("6.6.1.1. Grand Duke's static modifier updates immediately for current cards, new cards, and once Grand Duke leaves play.", () => {
      // Example A: The active player plays Grand Duke – Advisor to the King. He has an ability called Yes, Your Majesty that reads, “Your Prince, Princess, King, and Queen characters get +1 Ⓞ.” The +1 Ⓞ modifier generated by the ability’s effect applies immediately to the Ⓞ of all characters the active player has in play with the Prince, Princess, King, and Queen classifications. If that player plays another character with one of these classifications while their Grand Duke is still in play, the new character enters play with the +1 Ⓞ modifier applied and keeps that modification until the Grand Duke leaves play.
      const testEngine = LorcanaMultiplayerTestEngine.createWithFixture({
        hand: [grandDukeAdvisorToTheKing, thePrinceNeverGivesUp],
        inkwell: [
          controlYourTemper,
          improvise,
          lefouBumbler,
          mickeyMouseTrueFriend,
          simbaProtectiveCub,
        ],
        play: [tianaTruePrincess],
      });

      expect(testEngine.asPlayerOne().playCard(grandDukeAdvisorToTheKing)).toBeSuccessfulCommand();
      expect(testEngine.asPlayerOne().getCardStrength(tianaTruePrincess)).toBe(
        tianaTruePrincess.strength + 1,
      );

      expect(testEngine.asPlayerOne().playCard(thePrinceNeverGivesUp)).toBeSuccessfulCommand();
      expect(testEngine.asPlayerOne().getCardStrength(thePrinceNeverGivesUp)).toBe(
        thePrinceNeverGivesUp.strength + 1,
      );

      const grandDukeId = testEngine.findCardInstanceId(
        grandDukeAdvisorToTheKing,
        "play",
        PLAYER_ONE,
      );
      expect(
        testEngine.asServer().manualMoveCard(grandDukeId, `discard:${PLAYER_ONE}` as ZoneId)
          .success,
      ).toBe(true);

      expect(testEngine.asPlayerOne().getCardStrength(tianaTruePrincess)).toBe(
        tianaTruePrincess.strength,
      );
      expect(testEngine.asPlayerOne().getCardStrength(thePrinceNeverGivesUp)).toBe(
        thePrinceNeverGivesUp.strength,
      );
    });

    it("6.6.1.2. Multiple modifiers stack cumulatively, including after the running total becomes negative.", () => {
      const testEngine = LorcanaMultiplayerTestEngine.createWithFixture({
        hand: [controlYourTemper, controlYourTemper, improvise],
        inkwell: [mickeyMouseTrueFriend, lefouBumbler, minnieMouseBelovedPrincess],
        play: [{ card: simbaProtectiveCub, isDrying: false }],
        deck: [tianaTruePrincess],
      });

      expect(
        testEngine.asPlayerOne().playCard(controlYourTemper, { targets: [simbaProtectiveCub] })
          .success,
      ).toBe(true);
      expect(testEngine.asPlayerOne().getCardStrength(simbaProtectiveCub)).toBe(0);

      expect(
        testEngine.asPlayerOne().playCard(controlYourTemper, { targets: [simbaProtectiveCub] })
          .success,
      ).toBe(true);
      expect(testEngine.asPlayerOne().getCardStrength(simbaProtectiveCub)).toBe(-2);

      expect(
        testEngine.asPlayerOne().playCard(improvise, { targets: [simbaProtectiveCub] }).success,
      ).toBe(true);
      expect(testEngine.asPlayerOne().getCardStrength(simbaProtectiveCub)).toBe(-1);
    });

    it("6.6.2. Negative strength stays visible as raw state, but challenge and Yokai treat it as 0.", () => {
      // Example: The active player has a Yokai - Scientific Supervillain and a Microbots in play. Yokai has a triggered ability called Technical Gain that reads, "Whenever this character quests, draw a card for each opposing character with 0 Ⓞ." Microbots has a triggered ability called Inspired Tech that reads, "When you play this item, chosen character gets -1 Ⓞ this turn for each item named Microbots you have in play." The opponent has a character with 1 Ⓞ and 1 (W) in play. The active player plays a second Microbots. When resolving the triggered ability, the active player chooses the opponent's character, who immediately gets -2 Ⓞ and now has -1 Ⓞ and 1 Ⓞ. The active player then quests with Yokai. Because the opposing character's Ⓞ is negative, they count as having a Ⓞ of 0 when resolving Yokai's triggered ability, and the active player draws 1 card. Even though the character's Ⓞ counts as 0 for the purpose of resolving Yokai's effect, it isn't changed to 0; they still have a Ⓞ of -1.

      const testEngine = LorcanaMultiplayerTestEngine.createWithFixture(
        {
          hand: [microbots],
          inkwell: [controlYourTemper, improvise],
          play: [
            { card: yokaiScientificSupervillain, isDrying: false },
            microbots,
            { card: simbaProtectiveCub, isDrying: false },
          ],
          deck: [tianaTruePrincess],
        },
        {
          play: [{ card: lefouBumbler, exerted: true, isDrying: false }],
        },
      );

      const handMicrobots = testEngine.findCardInstanceId(microbots, "hand", PLAYER_ONE);
      const lefouId = testEngine.findCardInstanceId(lefouBumbler, "play", PLAYER_TWO);
      expect(
        testEngine.asPlayerOne().playCard(handMicrobots, { targets: [lefouBumbler] }).success,
      ).toBe(true);
      const [microbotsTrigger] = testEngine.asPlayerOne().getBagEffects();
      expect(
        testEngine
          .asPlayerOne()
          .resolvePendingByCard(microbotsTrigger!.sourceId, { targets: [lefouId] }).success,
      ).toBe(true);
      expect(testEngine.asPlayerTwo().getCardStrength(lefouBumbler)).toBe(-1);

      expect(testEngine.asPlayerOne().quest(yokaiScientificSupervillain)).toBeSuccessfulCommand();
      expect(testEngine.asPlayerOne().getCardsInZone("hand", PLAYER_ONE).count).toBe(1);

      expect(testEngine.asPlayerOne().challenge(simbaProtectiveCub, lefouBumbler).success).toBe(
        true,
      );
      expect(testEngine.asPlayerOne().getDamage(simbaProtectiveCub)).toBe(0);
    });

    it("6.6.3. Flynn's lore can go negative, but questing still gains 0 lore.", () => {
      // Example: The active player has a Flynn Rider – His Own Biggest Fan in play, and their opponent has 5 cards in their hand. Flynn has \(4 \downarrow\) and an ability called One Last, Big Score that reads, “This character gets \(-1 \downarrow\) for each card in your opponents’ hands.” Because the opponent has 5 cards in their hand, a modifier of -5 applies to Flynn’s Lore value of 4 (-1 for each of the 5 cards). Flynn now has a new Lore value of -1. Because Flynn’s Lore value is negative, if the player exerts him to quest, Flynn counts as having a Lore value of 0 and the player gains 0 lore. This doesn’t change Flynn’s actual Lore value to 0, however. Flynn still has a Lore value of -1 until the number of cards in the opponent’s hand changes or another modifier is applied to his Lore value.
      const testEngine = LorcanaMultiplayerTestEngine.createWithFixture(
        {
          play: [{ card: flynnRiderHisOwnBiggestFan, isDrying: false }],
        },
        {
          hand: [
            controlYourTemper,
            improvise,
            grandDukeAdvisorToTheKing,
            thePrinceNeverGivesUp,
            microbots,
          ],
        },
      );

      expect(testEngine.asServer().getCardLore(flynnRiderHisOwnBiggestFan)).toBe(-1);
      expect(
        testEngine.asServer().quest(PLAYER_ONE, flynnRiderHisOwnBiggestFan),
      ).toBeSuccessfulCommand();
      expect(testEngine.asServer().getLore(PLAYER_ONE)).toBe(0);
    });

    it("6.6.4. Elisa's printed-value floor applies after modifiers are combined and stops once the net result rises above printed strength.", () => {
      // Example: The active player has an Elisa Maza - Transformed Gargoyle in play with 4 and 4. She has a static ability called Forever Strong that reads, "Your characters' can't be reduced below their printed value." Elisa gets -4 until the end of her player's turn from an effect. After modifiers are applied, Elisa has a value of 0, but because that value is less than her printed value, her is 4. Later in the turn, Elisa gets +1 until the end of her player's turn from another effect. After both modifiers are applied, Elisa has a value of 1, but because this modified value is still lower than her printed value, her is 4. Later in the turn, Elisa gets +4 until the end of her player's turn from one last effect. After modifiers are applied, Elisa has a value of 5. Since this modified value isn't lower than her printed value of 4, Elisa has 5.
      const testEngine = LorcanaMultiplayerTestEngine.createWithFixture({
        hand: [controlYourTemper, controlYourTemper, improvise, improvise, standOut],
        inkwell: [
          mickeyMouseTrueFriend,
          lefouBumbler,
          minnieMouseBelovedPrincess,
          grandDukeAdvisorToTheKing,
          tianaTruePrincess,
          thePrinceNeverGivesUp,
          microbots,
        ],
        play: [{ card: elisaMazaTransformedGargoyle, isDrying: false }],
        deck: [simbaProtectiveCub, yokaiScientificSupervillain],
      });

      expect(
        testEngine
          .asPlayerOne()
          .playCard(controlYourTemper, { targets: [elisaMazaTransformedGargoyle] }).success,
      ).toBe(true);
      expect(testEngine.asPlayerOne().getCardStrength(elisaMazaTransformedGargoyle)).toBe(4);

      expect(
        testEngine
          .asPlayerOne()
          .playCard(controlYourTemper, { targets: [elisaMazaTransformedGargoyle] }).success,
      ).toBe(true);
      expect(testEngine.asPlayerOne().getCardStrength(elisaMazaTransformedGargoyle)).toBe(4);

      expect(
        testEngine.asPlayerOne().playCard(improvise, { targets: [elisaMazaTransformedGargoyle] })
          .success,
      ).toBe(true);
      expect(testEngine.asPlayerOne().getCardStrength(elisaMazaTransformedGargoyle)).toBe(4);

      expect(
        testEngine.asPlayerOne().playCard(standOut, { targets: [elisaMazaTransformedGargoyle] })
          .success,
      ).toBe(true);
      expect(testEngine.asPlayerOne().getCardStrength(elisaMazaTransformedGargoyle)).toBe(4);

      expect(
        testEngine.asPlayerOne().playCard(improvise, { targets: [elisaMazaTransformedGargoyle] })
          .success,
      ).toBe(true);
      expect(testEngine.asPlayerOne().getCardStrength(elisaMazaTransformedGargoyle)).toBe(5);
    });
  });
});
