//! Effect discriminators and the lossless `Effect` node.
//!
//! Mirrors the `Effect` and `StaticEffect` unions in
//! `oracle/source/packages/lorcana/lorcana-types/src/abilities/effect-types/`
//! (`combined-types.ts` aggregates members defined across `basic-effects.ts`,
//! `control-flow.ts`, `modifier-effects.ts`, `movement-effects.ts`, and
//! `scry-effects.ts`). Declaration order follows the `Effect` union, with the
//! three `StaticEffect`-only members (`self-play-condition`,
//! `grant-hand-inkability`, `grant-discard-inkability`) appended.
//!
//! Per-variant payload fields are preserved losslessly in the node's `rest` map.

use crate::macros::str_enum;
use crate::node::tagged_node;

str_enum! {
    /// The `type` discriminator of every [`Effect`] / `StaticEffect` variant.
    pub enum EffectType {
        Draw = "draw",
        Discard = "discard",
        Mill = "mill",
        Scry = "scry",
        DealDamage = "deal-damage",
        PutDamage = "put-damage",
        RemoveDamage = "remove-damage",
        MoveDamage = "move-damage",
        GainLore = "gain-lore",
        LoseLore = "lose-lore",
        Exert = "exert",
        Ready = "ready",
        Banish = "banish",
        SelectTarget = "select-target",
        ReturnToHand = "return-to-hand",
        ReturnRandomFromInkwell = "return-random-from-inkwell",
        ReturnFromDiscard = "return-from-discard",
        PutIntoInkwell = "put-into-inkwell",
        PutUnder = "put-under",
        ShuffleIntoDeck = "shuffle-into-deck",
        PutOnBottom = "put-on-bottom",
        MoveCardsFromUnder = "move-cards-from-under",
        PlayCard = "play-card",
        EnablePlayFromUnder = "enable-play-from-under",
        MoveToLocation = "move-to-location",
        MoveCostReduction = "move-cost-reduction",
        GrantAbilitiesWhileHere = "grant-abilities-while-here",
        ModifyStat = "modify-stat",
        StatFloor = "stat-floor",
        SetStat = "set-stat",
        DamageSourceStatOverride = "damage-source-stat-override",
        GainKeyword = "gain-keyword",
        LoseKeyword = "lose-keyword",
        Restriction = "restriction",
        GrantAbility = "grant-ability",
        CostReduction = "cost-reduction",
        CostIncrease = "cost-increase",
        NameACard = "name-a-card",
        RevealTopCard = "reveal-top-card",
        RevealUntilMatch = "reveal-until-match",
        PutOnTop = "put-on-top",
        DrawUntilHandSize = "draw-until-hand-size",
        Sequence = "sequence",
        Choice = "choice",
        Or = "or",
        Conditional = "conditional",
        Optional = "optional",
        ForEach = "for-each",
        Repeat = "repeat",
        RevealHand = "reveal-hand",
        RevealInkwell = "reveal-inkwell",
        SearchDeck = "search-deck",
        LookAtCards = "look-at-cards",
        PutInHand = "put-in-hand",
        EntersPlayModification = "enters-play-modification",
        WinConditionModification = "win-condition-modification",
        PropertyModification = "property-modification",
        CostEffect = "cost-effect",
        RevealAndConditional = "reveal-and-conditional",
        RevealAndRoute = "reveal-and-route",
        GrantKeyword = "grant-keyword",
        GrantKeywords = "grant-keywords",
        CreateTriggeredAbility = "create-triggered-ability",
        CreateReplacementEffect = "create-replacement-effect",
        PlayForFree = "play-for-free",
        PutOnDeck = "put-on-deck",
        Look = "look",
        PutIntoHand = "put-into-hand",
        Compound = "compound",
        ChallengeReady = "challenge-ready",
        Replacement = "replacement",
        ForEachOpponent = "for-each-opponent",
        ForEachPlayer = "for-each-player",
        PreventDamage = "prevent-damage",
        GainAbility = "gain-ability",
        GainKeywords = "gain-keywords",
        EntersPlayWith = "enters-play-with",
        RedirectDamage = "redirect-damage",
        AdditionalInkwell = "additional-inkwell",
        Move = "move",
        Triggered = "triggered",
        LookAtTop = "look-at-top",
        Modal = "modal",
        AddToInkwell = "add-to-inkwell",
        RevealTop = "reveal-top",
        PutCardUnder = "put-card-under",
        PayCost = "pay-cost",
        LookAtDeck = "look-at-deck",
        Prevention = "prevention",
        Count = "count",
        MoveToInkwell = "move-to-inkwell",
        EntersWithDamage = "enters-with-damage",
        Reveal = "reveal",
        TakeDamage = "take-damage",
        Support = "support",
        Protection = "protection",
        LoreLoss = "lore-loss",
        Heal = "heal",
        Search = "search",
        RevealDeck = "reveal-deck",
        DrawUntil = "draw-until",
        DiscardUntil = "discard-until",
        SuppressAbility = "suppress-ability",
        SelfPlayCondition = "self-play-condition",
        GrantHandInkability = "grant-hand-inkability",
        GrantDiscardInkability = "grant-discard-inkability",
    }
}

tagged_node! {
    /// A Lorcana effect node: typed `type` discriminator plus all other fields
    /// preserved losslessly.
    Effect, EffectType, crate::node::NodeFamily::Effect
}
