/**
 * Type declaration shim for generated Paraglide message module.
 *
 * The actual JS output is generated by `bun run i18n:compile` during build/checks.
 */
declare module "./paraglide/messages.js" {
  const messages: Record<
    string,
    (args?: Record<string, unknown>, options?: { locale?: string }) => string
  >;
  export = messages;
}
