/**
 * Oracle freeze — RNG/shuffle golden-vector generator (blueprint Step 0, §13.5).
 *
 * Exports TypeScript-oracle RNG vectors so the Rust port's seedrandom-compatible
 * RNG (Step 6) can be proven bit-for-bit against them. Generated from the pinned
 * frozen seedrandom@3.0.5; fails closed if the installed version differs.
 *
 *   bun run oracle/tools/gen-rng-golden.ts
 *
 * Output: oracle/golden/rng-golden-vectors.json (also regenerated by the freeze
 * writer). A committed fixture; the freeze tests regenerate and compare.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import {
  ARTIFACTS,
  EXPECTED_SEEDRANDOM_VERSION,
  GOLDEN_DIR,
  SEEDRANDOM_MODULE,
  installedSeedrandomVersion,
} from "./freeze-config";
import { type SeedrandomFactory, oracleRandomSequence, oracleShuffle } from "./rng-oracle";

// Deterministic, oracle-relevant cases: string + numeric-style seeds, and
// deck-sized shuffle inputs (Lorcana decks are 60 cards).
const RANDOM_SEEDS = ["", "0", "1", "abc", "lorcana", "seed:with:colons"];
const RANDOM_DRAWS = 12;
const SHUFFLE_SEEDS = ["abc", "lorcana", "42"];
const SHUFFLE_LENGTHS = [0, 1, 2, 10, 60];

function range(n: number): number[] {
  return Array.from({ length: n }, (_, i) => i);
}

export interface RngGoldenFixture {
  description: string;
  rulesetHash: string;
  seedrandomVersion: string;
  oracleSource: string;
  semantics: string;
  random: ReturnType<typeof oracleRandomSequence>;
  shuffle: ReturnType<typeof oracleShuffle>[];
}

export async function buildRngGolden(): Promise<RngGoldenFixture> {
  const installed = installedSeedrandomVersion();
  if (installed !== EXPECTED_SEEDRANDOM_VERSION) {
    throw new Error(
      `oracle rng golden: installed seedrandom ${installed} != pinned ` +
        `${EXPECTED_SEEDRANDOM_VERSION}; refusing to generate non-oracle vectors`,
    );
  }
  if (!existsSync(ARTIFACTS.rulesetHash)) {
    throw new Error("oracle rng golden: ruleset-hash.txt missing; run freeze-oracle.ts first");
  }
  const rulesetHash = readFileSync(ARTIFACTS.rulesetHash, "utf8").trim();

  const mod = (await import(SEEDRANDOM_MODULE)) as { default: SeedrandomFactory };
  const seedrandom = mod.default;

  const random = RANDOM_SEEDS.flatMap((s) => oracleRandomSequence(seedrandom, s, RANDOM_DRAWS));
  const shuffle = SHUFFLE_SEEDS.flatMap((s) =>
    SHUFFLE_LENGTHS.map((n) => oracleShuffle(seedrandom, s, range(n))),
  );

  return {
    description:
      "Frozen-oracle RNG/shuffle golden vectors. The Rust seedrandom-compatible " +
      "RNG (Step 6) must reproduce these exactly.",
    rulesetHash,
    seedrandomVersion: installed,
    oracleSource: "lorcana-engine/src/core/runtime/match-runtime.random-apis.ts",
    semantics:
      "random(): draws is incremented BEFORE computing, value = seedrandom(`${seed}:${draws}`)(). " +
      "shuffle(): Fisher-Yates, j = floor(random()*(i+1)) for i=len-1..1; consumes len-1 draws.",
    random,
    shuffle,
  };
}

export async function generateRngGolden(): Promise<void> {
  const fixture = await buildRngGolden();
  mkdirSync(GOLDEN_DIR, { recursive: true });
  writeFileSync(ARTIFACTS.rngGolden, `${JSON.stringify(fixture, null, 2)}\n`);
  console.log(
    `  wrote ${ARTIFACTS.rngGolden} ` +
      `(random=${fixture.random.length} shuffle=${fixture.shuffle.length}, ` +
      `seedrandom ${fixture.seedrandomVersion})`,
  );
}

if (import.meta.main) {
  await generateRngGolden();
}
