packages:
  - "packages/*"
  - "packages/lorcana/*"
  - "packages/tools/*"

catalog:
  vite: "npm:@voidzero-dev/vite-plus-core@0.1.21"
  vite-plus: 0.1.21
  vitest: "npm:@voidzero-dev/vite-plus-test@0.1.21"
  "@types/node": ^24.12.0
  typescript: ^5
  "@better-auth/infra": ^0.2.5
  better-auth: ^1.6.9
